---
- name: check os version
  fail: msg='OS is NOT Ubuntu 18.x'
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_major_version != '18'

- name: install packages
  apt:
    name:
      - python3-pip

- name: stop systemd-resolved
  systemd:
    name: systemd-resolved.service
    state: stopped
    enabled: no

- name: put resolv.conf
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
